<?php
    $title = $this->title . ' o setor';
    $this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url(
        'tropa',
        [
            'action' => 'save',
            'controller' => 'setor'
        ]));
    $form->prepare();
    echo $this->form()->openTag($form);

    /**
     * Forma de ordenar os campos
     * 
     * echo $this->formRow($form->get('codigo'));
     * echo $this->formRow($form->get('nome'));
     * echo $this->formSubmit($form->get('submit'));
     */

    /**
     * Adiciona os campos na ordem que foram criados
     */
    echo $this->formcollection($form);

    echo $this->form()->closeTag();
