<?php
    $this->headScript()->prependFile($this->basePath() . '/js/delete.js', 'text/javascript');

    $title = 'Setores';
    $this->headTitle($title);
?>
<h1><?=$this->escapeHtml($title)?></h1>
<p>
    <a href="<?=$this->url(
        'tropa',
        array(
            'action'=>'edit',
            'controller'=>'setor'
        )
    )?>">Novo setor</a>
</p>

<table class="table">
    <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($this->models as $model):?>
        <tr>
            <td><?=$model->codigo?></td>
            <td><?=$this->escapeHtml($model->nome)?></td>
            <td>
                <a href="<?=$this->url('tropa',
                    array(
                        'action'=>'edit',
                        'controller'=>'setor',
                        'key' => $model->codigo
                    )
                )?>">Editar</a>
                <button class="delete" url="<?=$this->url('tropa',
                    array(
                        'action'=>'delete',
                        'controller'=>'setor',
                        'key' => $model->codigo
                    )
                )?>">Remover</button>
            </td>
        </tr>
    <?php endforeach ?>
</table>