<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">

    <?= $this->headTitle('Sistema de Controle da Tropa dos Lanternas Verdes') ?>

    <!-- Styles -->
    <?= $this->headLink(
        array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath() . '/img/favicon.ico'
        )
    )->prependStylesheet($this->basePath() . '/css/tropa.css') ?>

    <!-- Scripts -->
    <?= $this->headScript()->prependFile($this->basePath() . '/js/jquery-3.1.0.min.js', 'text/javascript') ?>
    <?= $this->headScript()->prependFile($this->basePath() . '/js/bootstrap.min.js', 'text/javascript') ?>
</head>
<body>

    <header>
        <h1>Sistema de Controle da Tropa dos Lanternas Verdes</h1>
    </header>

    <div class="content">
        <?=$this->content?>
    </div>

    <footer>
        <p>&copy; <?= date('Y') ?> by Oa Sector 0 <?= $this->translate('All rights reserved.') ?></p>
    </footer>

</body>
</html>